# Generated by Django 2.2.7 on 2019-11-19 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_foreignkeymodel_jsonmodel_treemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondForeignKeyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('foreign_key_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.ForeignKeyModel')),
            ],
        ),
    ]
