# Generated by Django 2.2.7 on 2019-11-24 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_secondforeignkeymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UuidAsIdModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
