# Generated by Django 2.2.7 on 2019-11-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microframework', '0002_pendingobjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncdata',
            name='object_id',
            field=models.TextField(),
        ),
    ]

